export enum Category {
  All = "All",
  Payments = "Payments",
  NFTs = "NFTs",
  DeFi = "DeFi",
  DAO = "DAOs and Community",
  DeveloperTooling = "Developer Tooling",
  Infrastructure = "Infrastructure",
  Web3Social = "Web3 Social",
  RWA = "RWA",
  Gaming = "Gaming",
  AI = "AI",
  Content = "Content",
  UX = "User Experience",
}
